import {StyleSheet} from 'react-native';
import {screenHeight, MC, safeHeight, windowWidth, barHeight} from '../config/convert';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  safeView: {
    position: 'absolute',
    width: windowWidth,
    height: screenHeight - barHeight,
    top: barHeight,
    alignItems: 'center',
  },
  navView: {
    height: MC(88),
    width: windowWidth,
    justifyContent: 'center',
    alignItems: 'center',
  },
  navTitle: {
    color: '#001134',
    fontSize: MC(32),
    fontWeight: '500',
  },
  backIconView: {
    position: 'absolute',
    left: 0,
    width: MC(88),
    height: MC(88),
    justifyContent: 'center',
    alignItems: 'center',
  },
  backIcon: {
    position: 'absolute',
    left: MC(54),
    width: MC(12),
    height: MC(24),
  },
  mainView: {
    flex: 1,
    backgroundColor: '#F8FAFF',
    width: windowWidth,
    alignItems: 'center',
  },
  searchView: {
    width: MC(650),
    height: MC(92),
    backgroundColor: '#ffffff',
    borderRadius: MC(30),
    marginTop: MC(30),
    marginBottom: MC(30),
    justifyContent: 'center',
  },
  searchIcon: {
    position: 'absolute',
    right: MC(10),
    width: MC(72),
    height: MC(72),
  },
  searchIconImg: {
    width: MC(72),
    height: MC(72),
  },
  inputCode: {
    width: MC(500),
    height: MC(92),
    paddingLeft: MC(30),
    color: '#001133',
    fontSize: MC(24),
  },
  itemView: {
    flex: 1,
    width: windowWidth,
    backgroundColor: '#ffffff',
    borderTopLeftRadius: MC(40),
    borderTopRightRadius: MC(40),
    paddingBottom: MC(122),
  },
  itemContentView: {
    alignItems: 'center',
  },
  itemSearchView: {
    flex: 1,
    width: windowWidth,
    backgroundColor: '#F8FAFF',
  },
  itemTitle: {
    color: '#001133',
    width: windowWidth,
    fontSize: MC(32),
    fontWeight: '500',
    marginLeft: MC(100),
    marginTop: MC(40),
    marginBottom: MC(40),
  },
  itemInnerView: {
    width: windowWidth - MC(100),
    flex: 1,
  },
  itemTypeView: {
    minHeight: MC(186),
    width: windowWidth - MC(100),
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  IconView: {
    width: MC(174),
    height: MC(186),
    borderRadius: MC(50),
    alignItems: 'center',
  },
  searchItemIcon: {
    width: MC(76),
    height: MC(76),
    marginTop: MC(40),
  },
  searchItemText: {
    color: '#001133',
    fontSize: MC(24),
    fontWeight: '500',
    marginTop: MC(95),
  },
  itemType1View: {
    width: windowWidth - MC(100),
    marginTop: MC(40),
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  itemType2View: {
    width: windowWidth - MC(100),
    marginTop: MC(40),
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  itemTitle2: {
    color: '#001133',
    fontSize: MC(32),
    fontWeight: '500',
    marginBottom: MC(36),
  },
  itemBodyTypeView: {
    width: windowWidth - MC(100),
    height: MC(160),
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: MC(40),
  },
  itemSystemTypeView: {
    width: windowWidth - MC(100),
    height: MC(160),
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  itemBodyTypeInnerView: {
    width: MC(120),
    height: MC(160),
  },
  itemSystemTypeInnerView: {
    width: MC(120),
    height: MC(320),
  },
  itemBodyTypeInnerAvatarView: {
    width: MC(120),
    height: MC(120),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#001133',
    borderRadius: MC(100),
  },
  itemBodyTypeInnerText: {
    width: MC(120),
    height: MC(36),
    color: '#001133',
    fontSize: MC(22),
    marginTop: MC(16),
    textAlign: 'center',
  },
  bodyInnerIcon: {
    width: MC(110),
    height: MC(110),
  },
  searchTitle: {
    fontSize: MC(32),
    color: '#001133',
    fontWeight: 'bold',
    marginLeft: MC(50),
  },
  historyView: {
    width: windowWidth - MC(100),
    marginLeft: MC(50),
    marginTop: MC(30),
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  historyText: {
    height: MC(56),
    lineHeight: MC(56),
    backgroundColor: '#f5f5f5',
    borderRadius: MC(28),
    textAlign: 'center',
    paddingLeft: MC(40),
    paddingRight: MC(40),
    marginRight: MC(20),
    marginTop: MC(20),
  },
  itemNextView: {
    width: windowWidth - MC(100),
    flexDirection: 'row',
    // justifyContent: 'space-between',
    borderTopColor: '#E6E9F2',
    borderTopWidth: 1,
    flexWrap: 'wrap',
    paddingTop: MC(40),
    paddingBottom: MC(12),
  },
  nextText: {
    height: MC(56),
    lineHeight: MC(56),
    backgroundColor: '#f5f5f5',
    borderRadius: MC(28),
    textAlign: 'center',
    paddingLeft: MC(40),
    paddingRight: MC(40),
    marginRight: MC(20),
    marginBottom: MC(28),
  },
  saveBtn: {
    position: 'relative',
    marginTop: MC(30),
    width: MC(650),
    height: MC(100),
    backgroundColor: '#1FD1A2',
    borderRadius: MC(50),
    color: '#ffffff',
    fontSize: MC(28),
    textAlign: 'center',
    lineHeight: MC(100),
  },
});

export {styles};
