import {StyleSheet} from 'react-native';
import {MC, windowWidth, barHeight, screenHeight} from '../config/convert';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  topBg: {
    position: 'absolute',
    width: windowWidth,
    top: 0,
  },
  safeView: {
    width: windowWidth,
    height: screenHeight,
    marginTop: barHeight,
    flex: 1,
    justifyContent: 'space-between',
  },
  userInfoView: {
    position: 'relative',
    height: MC(192),
    width: windowWidth,
    justifyContent: 'center',
    alignItems: 'center',
  },
  userInfoTitle: {
    color: '#ffffff',
    fontSize: MC(36),
    fontWeight: '500',
  },
  userAvatar: {
    position: 'absolute',
    width: MC(96),
    height: MC(96),
    left: MC(50),
    borderRadius: MC(100),
    zIndex: 999,
  },
  userAvatarImg: {
    width: MC(96),
    height: MC(96),
    borderRadius: MC(100),
  },
  mainView: {
    position: 'relative',
    width: windowWidth,
    flex: 1,
    backgroundColor: '#F8FAFF',
    borderTopLeftRadius: MC(40),
    borderTopRightRadius: MC(40),
  },
  mainViewTitle: {
    position: 'relative',
    top: 0,
    height: MC(120),
    width: windowWidth,
  },
  mainViewCtrl: {
    position: 'relative',
    width: windowWidth,
    height: screenHeight - MC(456),
    alignItems: 'center',
    zIndex: 999,
  },
  userBodyInfoText: {
    width: MC(700),
    height: MC(120),
    backgroundColor: '#ffffff',
    borderRadius: MC(30),
    flexDirection: 'row',
  },
  infoListView: {
    position: 'absolute',
    width: windowWidth,
    height: screenHeight - MC(616) - barHeight,
    backgroundColor: '#F8FAFF',
    alignItems: 'center',
  },
  stateIcon: {
    position: 'absolute',
    left: MC(12),
    width: MC(56),
    height: MC(64),
  },
  stateBtn: {
    position: 'absolute',
    width: MC(144),
    height: MC(64),
    right: MC(36),
    top: MC(28),
    backgroundColor: '#1FD1A2',
    borderRadius: MC(16),
    justifyContent: 'center',
  },
  stateBtnText: {
    position: 'absolute',
    right: MC(16),
    color: '#ffffff',
  },
  screenBtn: {
    position: 'absolute',
    width: MC(144),
    height: MC(64),
    left: MC(36),
    top: MC(28),
    backgroundColor: '#ffffff',
    borderRadius: MC(16),
    justifyContent: 'center',
  },
  screenBtnLong: {
    position: 'absolute',
    width: MC(172),
    height: MC(64),
    left: MC(36),
    top: MC(28),
    backgroundColor: '#ffffff',
    borderRadius: MC(16),
    justifyContent: 'center',
  },
  screenIcon: {
    width: MC(56),
    height: MC(64),
    marginLeft: MC(4),
  },
  screenBtnText: {
    position: 'absolute',
    right: MC(16),
    color: '#000000',
  },
  indexBtnView: {
    position: 'relative',
    height: MC(144),
    width: windowWidth,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  indexBtn: {
    width: MC(700),
    height: MC(100),
    backgroundColor: '#1FD1A2',
    borderRadius: MC(50),
    justifyContent: 'center',
    alignItems: 'center',
  },
  indexBtnText: {
    color: '#ffffff',
  },
  infoItem: {
    flex: 1,
    alignItems: 'center',
    width: MC(120),
  },
  infoItemTitleText: {
    marginTop: MC(18),
    fontSize: MC(20),
    color: '#001133',
  },
  infoItemInner: {
    marginTop: MC(4),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: MC(120),
  },
  infoItemIcon: {
    position: 'relative',
    marginTop: MC(15),
    width: MC(20),
    height: MC(24),
  },
  infoItemText: {
    fontSize: MC(48),
    fontWeight: '500',
    color: '#000000',
    textAlign: 'center',
    width: MC(120),
  },
  userBtnAvatar: {
    position: 'absolute',
    left: MC(20),
    top: MC(14),
    width: MC(72),
    height: MC(72),
    borderRadius: MC(100),
  },
  addBtnView: {
    position: 'absolute',
    width: MC(112),
    height: MC(44),
    top: MC(28),
    right: MC(26),
    backgroundColor: '#ffffff',
    borderRadius: MC(22),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addIcon: {
    width: MC(20),
    height: MC(20),
  },
  addBtnText: {
    marginLeft: MC(10),
    color: '#1fd1a2',
    fontSize: MC(20),
    fontWeight: '500',
  },
  infoListItem: {
    width: MC(690),
    height: MC(160),
    borderRadius: MC(30),
    borderWidth: MC(1),
    borderColor: 'rgba(0,17,51,0.03)',
    backgroundColor: '#eafaf8',
    marginBottom: MC(20),
  },
  nodataDrew: {
    position: 'absolute',
    top: MC(34),
    width: MC(700),
    height: MC(700),
    alignItems: 'center',
  },
  manDrew: {
    position: 'absolute',
    width: MC(256),
    height: MC(800),
    alignItems: 'center',
  },
  bodyInner: {
    position: 'absolute',
    top: MC(120),
    height: MC(319),
    width: MC(114),
  },
  dynamicIcon: {
    position: 'absolute',
    left: MC(30),
    top: MC(32),
    width: MC(34),
    height: MC(32),
  },
  infoListItemTitle: {
    top: MC(30),
    left: MC(72),
    position: 'absolute',
    color: '#001133',
    fontSize: MC(28),
    fontWeight: '900',
  },
  infoListItemTime: {
    bottom: MC(30),
    left: MC(30),
    position: 'absolute',
    color: '#001133',
    opacity: 0.3,
    fontSize: MC(20),
  },
  infoListItemStateWait: {
    top: MC(30),
    right: MC(30),
    position: 'absolute',
    color: '#FF5151',
    fontSize: MC(28),
  },
  infoListItemStateMid: {
    top: MC(30),
    right: MC(30),
    position: 'absolute',
    color: '#FFA41B',
    fontSize: MC(28),
  },
  infoListItemStateBad: {
    top: MC(30),
    right: MC(30),
    position: 'absolute',
    color: '#FF5151',
    fontSize: MC(28),
  },
  screenView: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    zIndex: 999,
  },
  screenInnerView: {
    width: windowWidth,
    height: MC(980),
    backgroundColor: '#ffffff',
    borderTopLeftRadius: MC(40),
    borderTopRightRadius: MC(40),
    alignItems: 'center',
  },
  popCloseBtnView: {
    position: 'absolute',
    right: 0,
    top: 0,
    width: MC(120),
    height: MC(120),
    justifyContent: 'center',
    alignItems: 'center',
  },
  popCloseBtn: {
    width: MC(32),
    height: MC(32),
  },
  popTitle: {
    height: MC(120),
    fontSize: MC(32),
    lineHeight: MC(120),
    color: '#001133',
    fontWeight: '900',
  },
  popchooseView: {
    flex: 1,
    width: windowWidth - MC(76),
  },
  popchooseTitle: {
    fontSize: MC(28),
    color: '#001133',
    fontWeight: '900',
    marginLeft: MC(12),
  },
  popchooseStateView: {
    width: windowWidth - MC(76),
    height: MC(190),
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  popchooseStateItem: {
    width: MC(144),
    height: MC(60),
    borderRadius: MC(12),
    marginTop: MC(12),
    marginRight: MC(10),
    marginLeft: MC(10),
    backgroundColor: '#eceff4',
    justifyContent: 'center',
    alignItems: 'center',
  },
  popchooseStateItemText: {
    color: '#001133',
    fontSize: MC(24),
  },
  popchooseResetbtn: {
    position: 'absolute',
    bottom: MC(90),
    left: MC(50),
    width: MC(304),
    height: MC(88),
    borderRadius: MC(44),
    backgroundColor: '#ffffff',
    borderWidth: MC(2),
    borderColor: 'rgba(229,229,229,1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  popchooseBtnText: {
    color: '#001133',
    fontSize: MC(28),
    fontWeight: '900',
  },
  popchooseSubbtn: {
    poscition: 'absolute',
    bottom: MC(90),
    left: MC(182),
    width: MC(304),
    height: MC(88),
    borderRadius: MC(44),
    backgroundColor: '#1FD1A2',
    justifyContent: 'center',
    alignItems: 'center',
  },
  popchooseBtnText2: {
    color: '#ffffff',
    fontSize: MC(28),
    fontWeight: '900',
  },
  drawView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bodyWarImg: {
    position: 'absolute',
    height: MC(319),
    width: MC(114),
    top: 0,
    left: 0,
  },
  TipsViewHeart: {
    position: 'absolute',
    left: MC(58),
    top: MC(240),
    width: MC(256),
    height: MC(66),
    flexDirection: 'row',
  },
  TipsViewHead: {
    position: 'absolute',
    left: MC(-254),
    top: MC(100),
    width: MC(272),
    height: MC(78),
    flexDirection: 'row',
  },
  TipsViewNeck: {
    position: 'absolute',
    left: MC(-18),
    top: MC(140),
    width: MC(286),
    height: MC(94),
    flexDirection: 'row',
  },
  TipsViewLung: {
    position: 'absolute',
    right: MC(60),
    top: MC(240),
    width: MC(254),
    height: MC(58),
    flexDirection: 'row',
  },
  TipsViewLiver: {
    position: 'absolute',
    right: MC(60),
    top: MC(320),
    width: MC(270),
    height: MC(56),
    flexDirection: 'row',
  },
  TipsViewStomach: {
    position: 'absolute',
    left: MC(58),
    top: MC(320),
    width: MC(262),
    height: MC(52),
    flexDirection: 'row',
  },
  TipsViewHelperL: {
    position: 'absolute',
    right: MC(84),
    top: MC(380),
    width: MC(252),
    height: MC(66),
    flexDirection: 'row',
  },
  TipsViewHelperR: {
    position: 'absolute',
    left: MC(84),
    top: MC(380),
    width: MC(252),
    height: MC(66),
    flexDirection: 'row',
  },
  TipsViewKidney: {
    position: 'absolute',
    right: MC(40),
    top: MC(440),
    width: MC(276),
    height: MC(66),
    flexDirection: 'row',
  },
  TipsViewPancreas: {
    position: 'absolute',
    left: MC(20),
    top: MC(410),
    width: MC(314),
    height: MC(88),
    flexDirection: 'row',
  },
  TipsViewBladder: {
    position: 'absolute',
    right: MC(10),
    top: MC(520),
    width: MC(302),
    height: MC(60),
    flexDirection: 'row',
  },
  TipsViewEnteric: {
    position: 'absolute',
    left: MC(60),
    top: MC(490),
    width: MC(266),
    height: MC(76),
    flexDirection: 'row',
  },
  TipsViewGenital: {
    position: 'absolute',
    left: MC(-20),
    top: MC(500),
    width: MC(290),
    height: MC(132),
    flexDirection: 'row',
  },
  TipsViewLegL: {
    position: 'absolute',
    right: MC(20),
    top: MC(660),
    width: MC(252),
    height: MC(96),
    flexDirection: 'row',
  },
  TipsViewLegR: {
    position: 'absolute',
    left: MC(20),
    top: MC(660),
    width: MC(252),
    height: MC(96),
    flexDirection: 'row',
  },
  TipsInnerView: {
    width: MC(92),
    height: MC(44),
    borderWidth: 1,
    borderRadius: MC(8),
    alignItems: 'center',
    justifyContent: 'center',
  },
  TipsInnerText: {
    color: '#E83417',
    fontSize: MC(20),
  },
  lineBodyHead: {
    marginTop: MC(22),
    width: MC(180),
    height: MC(52),
  },
  lineBodyNeck: {
    marginTop: MC(22),
    width: MC(184),
    height: MC(72),
  },
  lineGutLung: {
    marginTop: MC(22),
    width: MC(162),
    height: MC(36),
  },
  lineGutLiver: {
    marginTop: MC(22),
    width: MC(178),
    height: MC(34),
  },
  lineGutStomach: {
    marginTop: MC(22),
    width: MC(170),
    height: MC(30),
  },
  lineBodyHelperL: {
    width: MC(160),
    height: MC(44),
  },
  lineGutHeart: {
    marginTop: MC(22),
    width: MC(164),
    height: MC(32),
  },
  lineGutKidney: {
    width: MC(184),
    height: MC(44),
  },
  lineGutPancreas: {
    width: MC(222),
    height: MC(66),
  },
  lineGutBladder: {
    width: MC(210),
    height: MC(38),
  },
  lineGutEnteric: {
    width: MC(174),
    height: MC(54),
  },
  lineBodyGenital: {
    width: MC(198),
    height: MC(110),
  },
  lineBodyLeg: {
    width: MC(160),
    height: MC(74),
  },
  bloodView: {
    position: 'absolute',
    right: MC(220),
    top: MC(20),
    width: MC(120),
    height: MC(44),
    borderWidth: 1,
    borderRadius: MC(8),
    borderColor: 'red',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bloodText: {
    color: 'red',
    fontSize: MC(20),
  },
  drawUpdataTimeText: {
    position: 'absolute',
    left: MC(50),
    top: MC(44),
    color: '#001133',
    opacity: 0.5,
    fontSize: MC(24),
  },
});

export {styles};
